import { StyleSheet } from "react-native";
import { responsiveFontSize, responsiveHeight, responsiveWidth } from "../../../utils/responsiveScale";
import { colors, fonts } from "../../../config/theme";

export const styles=StyleSheet.create(
    {
        btnMainContainer:{
            backgroundColor:"#f6f6f6",
            justifyContent:'center',
            borderRadius:responsiveHeight(1.5),
            paddingHorizontal:responsiveWidth(5),
            minHeight:responsiveHeight(8)
        },
        btn:{
            width:"100%",
            height:"100%",
            alignItems:"center",
            flexDirection:'row',
            justifyContent:'space-between',
        },
        classIDBtn:{
            alignItems:"center",
            flexDirection:'row',
            justifyContent:'space-between',
        },
        btnText:{
            fontSize:responsiveWidth(4.5),
            color:colors.gray,
            fontFamily:fonts.textFont,
        },
        dropDownListContainer:{
            borderWidth:1,
            minHeight:responsiveHeight(15)
        },
        eachListItem:{
            paddingLeft:responsiveWidth(5),
            paddingVertical:responsiveHeight(0.1)
        },
        textInputContainer:{
            backgroundColor:"#f6f6f6",
            justifyContent:'center',
            borderRadius:responsiveHeight(1.5),
            paddingHorizontal:responsiveHeight(2)
        },
        textInputFont:{
            fontSize:responsiveWidth(4.2),
            fontFamily:fonts.primary,
            color:colors.primary
        },
        eachListText:{
            fontSize:responsiveWidth(4),
            fontFamily:fonts.textInput,
            color:colors.primary
        },
        btnorTextInput:{
           paddingHorizontal:responsiveHeight(2),
           justifyContent:'center',
           borderRadius:responsiveHeight(1.5),
           backgroundColor:"#f6f6f6",
           minHeight:responsiveHeight(8)
        },
        selectedAirportContainer:{
            flex:1,
            justifyContent:'center',
            rowGap:responsiveHeight(0.5)
        },
        title:{
            fontSize:responsiveWidth(4),
            fontFamily:fonts.primary,
            color:colors.primary
        },
        subTitle:{
            fontSize:responsiveWidth(2.6),
            fontFamily:fonts.textFont,
            color:"#969696"
        }
    }
)